set_property SRC_FILE_INFO {cfile:/home/dev/VivadoProjects/Genesys2_RO/Genesys2_RO.srcs/constrs_1/new/Genesys2_Master.xdc rfile:../../../Genesys2_RO.srcs/constrs_1/new/Genesys2_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not00_i_1]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X145Y349 [get_cells not00_i_1]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not0_i_1]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y0 [get_cells not0_i_1]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells not0/Y_INST_0]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y0 [get_cells not0/Y_INST_0]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells not1/Y_INST_0]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y0 [get_cells not1/Y_INST_0]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells not2/Y_INST_0]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y0 [get_cells not2/Y_INST_0]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not3/Y_INST_0]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y0 [get_cells not3/Y_INST_0]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells not4/Y_INST_0]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y0 [get_cells not4/Y_INST_0]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells not5/Y_INST_0]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y0 [get_cells not5/Y_INST_0]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells not6/Y_INST_0]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y0 [get_cells not6/Y_INST_0]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not7/Y_INST_0]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X2Y0 [get_cells not7/Y_INST_0]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells not8/Y_INST_0]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X2Y0 [get_cells not8/Y_INST_0]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells not9/Y_INST_0]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X2Y0 [get_cells not9/Y_INST_0]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells not10/Y_INST_0]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X2Y0 [get_cells not10/Y_INST_0]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not000_i_1]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y349 [get_cells not000_i_1]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not0000_i_1]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X150Y0 [get_cells not0000_i_1]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells not0000/Y_INST_0]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X150Y0 [get_cells not0000/Y_INST_0]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells not0001/Y_INST_0]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X150Y0 [get_cells not0001/Y_INST_0]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells not0002/Y_INST_0]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X150Y0 [get_cells not0002/Y_INST_0]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not0003/Y_INST_0]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X151Y0 [get_cells not0003/Y_INST_0]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells not0004/Y_INST_0]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X151Y0 [get_cells not0004/Y_INST_0]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells not0005/Y_INST_0]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X151Y0 [get_cells not0005/Y_INST_0]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells not0006/Y_INST_0]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X151Y0 [get_cells not0006/Y_INST_0]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not0007/Y_INST_0]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X152Y0 [get_cells not0007/Y_INST_0]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells not0008/Y_INST_0]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X152Y0 [get_cells not0008/Y_INST_0]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells not0009/Y_INST_0]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X152Y0 [get_cells not0009/Y_INST_0]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells not00010/Y_INST_0]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X152Y0 [get_cells not00010/Y_INST_0]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not00011/Y_INST_0]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X153Y0 [get_cells not00011/Y_INST_0]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells not00012/Y_INST_0]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X153Y0 [get_cells not00012/Y_INST_0]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells not00013/Y_INST_0]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X153Y0 [get_cells not00013/Y_INST_0]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells not00014/Y_INST_0]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X153Y0 [get_cells not00014/Y_INST_0]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not00000_i_1]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y337 [get_cells not00000_i_1]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not000000_i_1]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y312 [get_cells not000000_i_1]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells not000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y312 [get_cells not000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not0000000_i_1]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y287 [get_cells not0000000_i_1]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells not0000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y287 [get_cells not0000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not00000000_i_1]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y262 [get_cells not00000000_i_1]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells not00000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y262 [get_cells not00000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not000000000_i_1]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y237 [get_cells not000000000_i_1]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells not000000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y237 [get_cells not000000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not0000000000_i_1]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y212 [get_cells not0000000000_i_1]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells not0000000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y212 [get_cells not0000000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not00000000000_i_1]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y187 [get_cells not00000000000_i_1]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells not00000000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y187 [get_cells not00000000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not000000000000_i_1]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y162 [get_cells not000000000000_i_1]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells not000000000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y162 [get_cells not000000000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not0000000000000_i_1]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X114Y337 [get_cells not0000000000000_i_1]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells not0000000000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X114Y337 [get_cells not0000000000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not00000000000000_i_1]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X114Y312 [get_cells not00000000000000_i_1]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells not00000000000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X114Y312 [get_cells not00000000000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not000000000000000_i_1]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X114Y287 [get_cells not000000000000000_i_1]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells not000000000000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X114Y287 [get_cells not000000000000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not0000000000000000_i_1]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X114Y262 [get_cells not0000000000000000_i_1]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells not0000000000000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X114Y262 [get_cells not0000000000000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not00000000000000000_i_1]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X114Y237 [get_cells not00000000000000000_i_1]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells not00000000000000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X114Y237 [get_cells not00000000000000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not000000000000000000_i_1]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X114Y212 [get_cells not000000000000000000_i_1]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells not000000000000000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X114Y212 [get_cells not000000000000000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not0000000000000000000_i_1]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X114Y187 [get_cells not0000000000000000000_i_1]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells not0000000000000000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X114Y187 [get_cells not0000000000000000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells not00000000000000000000_i_1]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X114Y162 [get_cells not00000000000000000000_i_1]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells not00000000000000000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X114Y162 [get_cells not00000000000000000003/Y_INST_0]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL AFF [get_cells counter_reg[0]]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X153Y1 [get_cells counter_reg[0]]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL AFF [get_cells counter_reg[1]]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X153Y2 [get_cells counter_reg[1]]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL AFF [get_cells counter_reg[2]]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X153Y3 [get_cells counter_reg[2]]
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL AFF [get_cells counter_reg[3]]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X153Y4 [get_cells counter_reg[3]]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells counter[0]_i_1]
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X145Y1 [get_cells counter[0]_i_1]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells counter[1]_i_1]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X145Y1 [get_cells counter[1]_i_1]
set_property src_info {type:XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells counter[2]_i_1]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X145Y1 [get_cells counter[2]_i_1]
set_property src_info {type:XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells counter[3]_i_1]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X145Y1 [get_cells counter[3]_i_1]
set_property src_info {type:XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells counter[3]_i_2]
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X144Y1 [get_cells counter[3]_i_2]
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AD11  IOSTANDARD LVDS  } [get_ports { clk_n }]; #IO_L12N_T1_MRCC_33 Sch=sysclk_n
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AD12  IOSTANDARD LVDS } [get_ports { clk_p }]; #IO_L12P_T1_MRCC_33 Sch=sysclk_p
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U30 IOSTANDARD LVCMOS33} [get_ports {led[2]}];
set_property src_info {type:XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U29 IOSTANDARD LVCMOS33} [get_ports {led[3]}];
set_property src_info {type:XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVCMOS33} [get_ports {led[4]}];
set_property src_info {type:XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V26 IOSTANDARD LVCMOS33} [get_ports {led[5]}];
set_property src_info {type:XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W24 IOSTANDARD LVCMOS33} [get_ports {led[6]}];
set_property src_info {type:XDC file:1 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W23 IOSTANDARD LVCMOS33} [get_ports {led[7]}]; #IO_L20P_T3_A08_D24_14 Sch=led[7]
set_property src_info {type:XDC file:1 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H24   IOSTANDARD LVCMOS12} [get_ports { R_in } ];
set_property src_info {type:XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K19   IOSTANDARD LVCMOS12} [get_ports { R_in1 } ];
set_property src_info {type:XDC file:1 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN N19   IOSTANDARD LVCMOS12} [get_ports { R_in2 } ];
set_property src_info {type:XDC file:1 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P19   IOSTANDARD LVCMOS12} [get_ports { R_in3 } ];
set_property src_info {type:XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P26   IOSTANDARD LVCMOS33} [get_ports { R_in4 } ];
set_property src_info {type:XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P27   IOSTANDARD LVCMOS33 } [get_ports { reset }]; #IO_L8P_T1_D11_14 Sch=sw[7]
set_property src_info {type:XDC file:1 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U27 IOSTANDARD LVCMOS33} [get_ports R_out]
set_property src_info {type:XDC file:1 line:408 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U28 IOSTANDARD LVCMOS33} [get_ports R_out1]
set_property src_info {type:XDC file:1 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T26 IOSTANDARD LVCMOS33} [get_ports R_out2]
set_property src_info {type:XDC file:1 line:410 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T27 IOSTANDARD LVCMOS33} [get_ports R_out3]
set_property src_info {type:XDC file:1 line:411 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T22 IOSTANDARD LVCMOS33} [get_ports R_out4]
set_property src_info {type:XDC file:1 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T23 IOSTANDARD LVCMOS33} [get_ports R_out5]
set_property src_info {type:XDC file:1 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33} [get_ports R_out6]
set_property src_info {type:XDC file:1 line:414 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T21 IOSTANDARD LVCMOS33} [get_ports R_out7]
set_property src_info {type:XDC file:1 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V29 IOSTANDARD LVCMOS33} [get_ports R_out8]
set_property src_info {type:XDC file:1 line:418 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V30 IOSTANDARD LVCMOS33} [get_ports R_out9]
set_property src_info {type:XDC file:1 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V25 IOSTANDARD LVCMOS33} [get_ports R_out10]
set_property src_info {type:XDC file:1 line:420 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W26 IOSTANDARD LVCMOS33} [get_ports R_out11]
set_property src_info {type:XDC file:1 line:421 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T25 IOSTANDARD LVCMOS33} [get_ports R_out12]
set_property src_info {type:XDC file:1 line:422 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U25 IOSTANDARD LVCMOS33} [get_ports R_out13]
set_property src_info {type:XDC file:1 line:423 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U22 IOSTANDARD LVCMOS33} [get_ports R_out14]
set_property src_info {type:XDC file:1 line:424 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U23 IOSTANDARD LVCMOS33} [get_ports R_out15]
set_property src_info {type:XDC file:1 line:427 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC26 IOSTANDARD LVCMOS33} [get_ports counter[0]]
set_property src_info {type:XDC file:1 line:428 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AJ27 IOSTANDARD LVCMOS33} [get_ports counter[1]]
set_property src_info {type:XDC file:1 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AH30 IOSTANDARD LVCMOS33} [get_ports counter[2]]
set_property src_info {type:XDC file:1 line:430 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AK29 IOSTANDARD LVCMOS33} [get_ports counter[3]]
set_property src_info {type:XDC file:1 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V27   IOSTANDARD LVCMOS33 } [get_ports { R_out16 }]; #IO_L16N_T2_A15_D31_14 Sch=jd[1]
set_property src_info {type:XDC file:1 line:438 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN Y30   IOSTANDARD LVCMOS33 } [get_ports { R_out17 }]; #IO_L8P_T1_13 Sch=jd[2]
set_property src_info {type:XDC file:1 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V24   IOSTANDARD LVCMOS33 } [get_ports { R_out18 }]; #IO_L23N_T3_A02_D18_14 Sch=jd[3]
set_property src_info {type:XDC file:1 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W22   IOSTANDARD LVCMOS33 } [get_ports { R_out19 }]; #IO_L24N_T3_A00_D16_14 Sch=jd[4]
